### ISSUE TITLE
Problem with log4js configuration:

### ISSUE THREAD

**Issue by Bliizzer10** [Bliizzer10/Problem-with-log4js-configuration#1]
Hello :) 
i have a problem i wanto to start my site.js and it come this Problem:

Error: Problem with log4js configuration: ({ appenders:
   [ { type: 'console' },
     { type: 'file', filename: 'logs/site.log' } ] }) - must have a property "appenders" of type object.
    at tests.forEach (/var/www/bot/node_modules/log4js/lib/configuration.js:38:15)
    at Array.forEach (native)
    at Configuration.throwExceptionIf (/var/www/bot/node_modules/log4js/lib/configuration.js:36:11)
    at new Configuration (/var/www/bot/node_modules/log4js/lib/configuration.js:199:10)
    at Object.configure (/var/www/bot/node_modules/log4js/lib/log4js.js:195:12)
    at Object.<anonymous> (/var/www/bot/site.js:10:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by Bliizzer10** [comment]
Can someone help me there? :/
